//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectpdf1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback_
    {
        public int Id { get; set; }
        public Nullable<int> FromTL { get; set; }
        public Nullable<int> ToPM { get; set; }
        public Nullable<int> OnJE { get; set; }
        public string Feedback { get; set; }
        public Nullable<int> TeamID { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
