//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectpdf1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiringRequest
    {
        public int R_Id { get; set; }
        public int Project_id { get; set; }
        public int User_id { get; set; }
        public int State_id { get; set; }
        public int RequestType { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Request_type Request_type { get; set; }
        public virtual User User { get; set; }
    }
}
