//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectpdf1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMrealstateEntities : DbContext
    {
        public PMrealstateEntities()
            : base("name=PMrealstateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<feedback_> feedback_ { get; set; }
        public virtual DbSet<HiringRequest> HiringRequests { get; set; }
        public virtual DbSet<Onprogresstate> Onprogresstates { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Request_type> Request_type { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<User_Role> User_Role { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersAccepet> UsersAccepets { get; set; }
    }
}
