//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectpdf1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.HiringRequests = new HashSet<HiringRequest>();
            this.Projects = new HashSet<Project>();
            this.UsersAccepets = new HashSet<UsersAccepet>();
        }
    
        public int U_Id { get; set; }
        public string U_FName { get; set; }
        public string ULName { get; set; }
        public string U_Email { get; set; }
        public Nullable<int> U_Phone { get; set; }
        public string U_Password { get; set; }
        public string U_Job { get; set; }
        public string U_Pathphoto { get; set; }
        public Nullable<int> Type_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HiringRequest> HiringRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
        public virtual User_Role User_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersAccepet> UsersAccepets { get; set; }
    }
}
