//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectpdf1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAccepet
    {
        public int UAcc_Id { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> Project_id { get; set; }
        public Nullable<int> state_id { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual State State { get; set; }
        public virtual User User { get; set; }
    }
}
